site_name: Cycling Beats - Documentation
nav:
  - Home: "index.md"
  - Installation Guide - Dev: "dev_install.md"
  - Tools: "tools.md"
  - Examples: "examples.md"
  - Checklist: "checklist.md"
theme:
  name: material
  logo: assets/logo.jpg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/timpandrews

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://justtim.com"  target="_blank" rel="noopener">justtim.com</a>