site_name: Cycling Beats - Documentation
nav:
  - Home: "index.md"
  - Conventions: "conventions.md"
  - Install Guides: "install_guides.md"
  - Tasks: "tasks.md"
  - Tools: "tools.md"
  - Dependencies: "dependencies.md"
  - Beats-Tools: "beats_tools.md"
  - Beats-Docs: "beats_docs.md"
  - Misc.: "misc.md"
  - Extras: "extras.md"
  
theme:
  name: material
  logo: assets/logo.jpg
  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: deep purple
      accent: teal 
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: deep purple
      accent: teal

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/timpandrews

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

copyright: |
  &copy; 2024 <a href="https://justtim.com"  target="_blank" rel="noopener">justtim.com</a>